# Generated by Django 5.1.15 on 2026-02-27 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('is_corrected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='homework_posts', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_posts', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_posts', to='grades.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homework_posts',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='homework/attachments/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO_LINK', 'Video Link')], max_length=12)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.homeworkpost')),
            ],
            options={
                'db_table': 'homework_attachments',
            },
        ),
        migrations.CreateModel(
            name='HomeworkView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='homework.homeworkpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_views', to='academics.studentprofile')),
            ],
            options={
                'db_table': 'homework_views',
                'unique_together': {('student', 'homework')},
            },
        ),
    ]
