# Generated by Django 5.1.15 on 2026-03-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        ('schools', '0003_alter_academicyear_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkpost',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_posts', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='homeworkpost',
            name='assigned_date',
            field=models.DateField(blank=True, help_text='Date the homework was assigned (auto-set to creation date).', null=True),
        ),
        migrations.AddField(
            model_name='homeworkpost',
            name='delete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homeworkpost',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete (in minutes).', null=True),
        ),
        migrations.AddField(
            model_name='homeworkpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homeworkpost',
            name='due_date',
            field=models.DateField(help_text='Deadline date for the homework.'),
        ),
    ]
