# Generated by Django 5.1.15 on 2026-03-04 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_is_custom'),
        ('homework', '0002_add_fields_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkpost',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_posts', to='academics.subject'),
        ),
    ]
