# Generated by Django 5.1.15 on 2026-02-27 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.section')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trimester', models.IntegerField(choices=[(1, 'Trimester 1'), (2, 'Trimester 2'), (3, 'Trimester 3')])),
                ('exam_type', models.CharField(choices=[('CONTINUOUS', 'Continuous Assessment'), ('TEST_1', 'Test 1'), ('TEST_2', 'Test 2'), ('FINAL', 'Final Exam')], max_length=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_value', models.DecimalField(decimal_places=2, default='20.00', max_digits=4)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('PUBLISHED', 'Published'), ('RETURNED', 'Returned')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grades', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.studentprofile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.subject')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trimester', models.IntegerField(choices=[(1, 'Trimester 1'), (2, 'Trimester 2'), (3, 'Trimester 3')])),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True, help_text='Signed URL of the generated PDF on S3 / R2.', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='schools.academicyear')),
                ('class_obj', models.ForeignKey(db_column='class_id', help_text='Class at the time the report was generated (historical record).', on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.studentprofile')),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'academic_year', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='TrimesterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('continuous_weight', models.DecimalField(decimal_places=2, default='0.20', max_digits=4)),
                ('test1_weight', models.DecimalField(decimal_places=2, default='0.20', max_digits=4)),
                ('test2_weight', models.DecimalField(decimal_places=2, default='0.20', max_digits=4)),
                ('final_weight', models.DecimalField(decimal_places=2, default='0.40', max_digits=4)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_configs', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_configs', to='schools.section')),
            ],
            options={
                'db_table': 'trimester_configs',
                'unique_together': {('school', 'section')},
            },
        ),
    ]
