# Generated by Django 5.1.15 on 2026-03-04 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_is_custom'),
        ('grades', '0001_initial'),
        ('schools', '0004_school_available_streams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['exam_type__trimester', 'exam_type__name'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bulletin scolaire', 'verbose_name_plural': 'Bulletins scolaires'},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='created_at',
            new_name='entered_at',
        ),
        migrations.AddField(
            model_name='grade',
            name='entered_by',
            field=models.ForeignKey(help_text='Enseignant ou admin ayant saisi la note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_absent',
            field=models.BooleanField(default=False, help_text='Absent = note comptée comme 0'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Publié aux élèves/parents'),
        ),
        migrations.AddField(
            model_name='grade',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note obtenue (null = pas encore saisie)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', help_text='Class at the time the report was generated.', on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.class'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='trimester',
            field=models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')]),
        ),
        migrations.AlterModelTable(
            name='grade',
            table='student_grades',
        ),
        migrations.CreateModel(
            name='AnnualAverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manual_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('rank_in_level', models.IntegerField(blank=True, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_averages', to='schools.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_averages', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_averages', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Moyenne annuelle',
                'verbose_name_plural': 'Moyennes annuelles',
                'db_table': 'annual_averages',
                'ordering': ['rank_in_class'],
                'unique_together': {('student', 'classroom', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trimester', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')])),
                ('name', models.CharField(help_text='Ex: "Examen 1", "Contrôle Continu", "Devoir Surveillé"', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Pourcentage de cet examen dans la moyenne (ex: 60.00)', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=20, help_text="Barème de l'examen (/20, /10, etc.)", max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='schools.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='academics.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_types', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='academics.subject')),
            ],
            options={
                'verbose_name': "Type d'examen",
                'verbose_name_plural': "Types d'examens",
                'db_table': 'exam_types',
                'ordering': ['trimester', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.examtype'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'exam_type')},
        ),
        migrations.CreateModel(
            name='SubjectAverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trimester', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')])),
                ('calculated_average', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne calculée automatiquement', max_digits=5, null=True)),
                ('manual_override', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne saisie manuellement (remplace la calculée)', max_digits=5, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='schools.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='academics.class')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_subject_avgs', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_subject_avgs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Moyenne matière',
                'verbose_name_plural': 'Moyennes matières',
                'db_table': 'subject_averages',
                'ordering': ['trimester', 'subject__name'],
                'unique_together': {('student', 'subject', 'classroom', 'academic_year', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='TrimesterAverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trimester', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')])),
                ('calculated_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manual_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('rank_in_stream', models.IntegerField(blank=True, help_text='Rang dans la filière (lycée uniquement)', null=True)),
                ('rank_in_level', models.IntegerField(blank=True, help_text='Rang dans le niveau (ex: tous les 1AM)', null=True)),
                ('rank_in_section', models.IntegerField(blank=True, help_text='Rang dans la section (Primaire/CEM/Lycée)', null=True)),
                ('appreciation', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_averages', to='schools.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_averages', to='academics.class')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_trim_avgs', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_trim_avgs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_averages', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Moyenne trimestrielle',
                'verbose_name_plural': 'Moyennes trimestrielles',
                'db_table': 'trimester_averages',
                'ordering': ['trimester', 'rank_in_class'],
                'unique_together': {('student', 'classroom', 'academic_year', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='GradeAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_type', models.CharField(choices=[('EXAM_GRADE', "Note d'examen"), ('SUBJECT_AVERAGE', 'Moyenne de matière'), ('TRIMESTER_AVERAGE', 'Moyenne de trimestre'), ('ANNUAL_AVERAGE', 'Moyenne annuelle')], max_length=20)),
                ('reason', models.TextField(help_text="Raison du recours saisie par l'élève/parent")),
                ('student_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('UNDER_REVIEW', 'En cours de traitement'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('assigned_to_admin', models.BooleanField(default=False, help_text='Pour moyennes générales')),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('corrected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_teacher', models.ForeignKey(blank=True, help_text='Pour notes/moyennes matière', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appeals', to='academics.teacherprofile')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='grades.grade')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_responses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_appeals', to='academics.studentprofile')),
                ('subject_average', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='grades.subjectaverage')),
                ('trimester_average', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='grades.trimesteraverage')),
            ],
            options={
                'verbose_name': 'Recours',
                'verbose_name_plural': 'Recours',
                'db_table': 'grade_appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TrimesterConfig',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='trimester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='value',
        ),
    ]
