# Generated by Django 5.1.15 on 2026-03-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_subject_class_obj_remove_subject_created_by_and_more'),
        ('homework', '0003_alter_homeworkpost_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
