# Generated by Django 5.1.15 on 2026-03-04 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_is_custom'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('grades', '0003_delete_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('GRADE_ENTERED', 'Note saisie'), ('GRADE_CORRECTED', 'Note corrigée'), ('GRADE_PUBLISHED', 'Notes publiées'), ('AVERAGE_CALCULATED', 'Moyenne calculée'), ('AVERAGE_OVERRIDDEN', 'Moyenne modifiée manuellement'), ('AVERAGE_PUBLISHED', 'Moyenne publiée'), ('TRIMESTER_LOCKED', 'Trimestre verrouillé'), ('TRIMESTER_UNLOCKED', 'Trimestre déverrouillé'), ('APPEAL_CREATED', 'Recours créé'), ('APPEAL_ACCEPTED', 'Recours accepté'), ('APPEAL_REJECTED', 'Recours rejeté')], max_length=30)),
                ('object_id', models.UUIDField()),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True)),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('exam_name', models.CharField(blank=True, max_length=200)),
                ('trimester', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_audit_logs', to='contenttypes.contenttype')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_audit_logs', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': "Journal d'audit notes",
                'verbose_name_plural': "Journaux d'audit notes",
                'db_table': 'grade_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='grade_audit_student_bfc5d4_idx'), models.Index(fields=['content_type', 'object_id'], name='grade_audit_content_1a8c64_idx')],
            },
        ),
    ]
