# Generated by Django 5.1.15 on 2026-03-05 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_add_grade_audit_log'),
        ('schools', '0004_school_available_streams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='admin_comment',
            field=models.TextField(blank=True, default='', help_text="Commentaire de l'admin lors du rejet"),
        ),
        migrations.AddField(
            model_name='grade',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('PUBLISHED', 'Publié'), ('RETURNED', 'Retourné')], db_index=True, default='DRAFT', help_text='État du workflow (DRAFT → SUBMITTED → PUBLISHED / RETURNED)', max_length=12),
        ),
        migrations.AddField(
            model_name='grade',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradeauditlog',
            name='action',
            field=models.CharField(choices=[('GRADE_ENTERED', 'Note saisie'), ('GRADE_CORRECTED', 'Note corrigée'), ('GRADE_SUBMITTED', 'Notes soumises'), ('GRADE_PUBLISHED', 'Notes publiées'), ('GRADE_RETURNED', 'Notes retournées'), ('GRADE_CSV_IMPORTED', 'Notes importées par CSV'), ('AVERAGE_CALCULATED', 'Moyenne calculée'), ('AVERAGE_OVERRIDDEN', 'Moyenne modifiée manuellement'), ('AVERAGE_PUBLISHED', 'Moyenne publiée'), ('TRIMESTER_LOCKED', 'Trimestre verrouillé'), ('TRIMESTER_UNLOCKED', 'Trimestre déverrouillé'), ('APPEAL_CREATED', 'Recours créé'), ('APPEAL_ACCEPTED', 'Recours accepté'), ('APPEAL_REJECTED', 'Recours rejeté')], max_length=30),
        ),
        migrations.CreateModel(
            name='TrimesterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_t1', models.DecimalField(decimal_places=2, default=1, help_text='Pondération du trimestre 1', max_digits=4)),
                ('weight_t2', models.DecimalField(decimal_places=2, default=1, help_text='Pondération du trimestre 2', max_digits=4)),
                ('weight_t3', models.DecimalField(decimal_places=2, default=1, help_text='Pondération du trimestre 3', max_digits=4)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Nombre de décimales pour les moyennes (1 ou 2)')),
                ('pass_threshold', models.DecimalField(decimal_places=2, default=10, help_text='Seuil de passage (défaut: 10/20)', max_digits=4)),
                ('use_level_subject_coefficients', models.BooleanField(default=True, help_text='Utiliser les coefficients de LevelSubject (défaut: oui)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Configuration trimestrielle',
                'verbose_name_plural': 'Configurations trimestrielles',
                'db_table': 'trimester_configs',
            },
        ),
    ]
