# Generated by Django 5.1.15 on 2026-03-02 23:03

import apps.schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='has_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_middle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='max_students',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_category',
            field=models.CharField(choices=[('PRIVATE_SCHOOL', 'École Privée'), ('TRAINING_CENTER', 'Centre de Formation')], default='PRIVATE_SCHOOL', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='training_type',
            field=models.CharField(blank=True, choices=[('SUPPORT_COURSES', 'Cours de Soutien Scolaire'), ('LANGUAGES', 'École de Langues'), ('PROFESSIONAL', 'Formation Professionnelle'), ('EXAM_PREP', 'Préparation aux Examens (BEM/BAC)'), ('COMPUTING', 'Informatique & Bureautique'), ('OTHER', 'Autre')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/', validators=[apps.schools.models.validate_school_logo]),
        ),
    ]
