# Generated by Django 5.1.15 on 2026-03-03 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_has_high_school_has_middle_school_has_primary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.section'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('school', 'section', 'name'), name='unique_school_section_year'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('school', 'name'), name='unique_school_year_no_section'),
        ),
    ]
