# Generated by Django 5.1.15 on 2026-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_available_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='absence_alert_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Number of monthly unjustified absences that trigger a chronic-absenteeism alert.'),
        ),
    ]
