# Generated by Django 5.1.15 on 2026-03-03 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('schools', '0003_alter_academicyear_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='installment_count',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='is_installment_allowed',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='target_class',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='amount_annual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Full annual amount (DZD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='amount_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly instalment amount (DZD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='amount_trimester',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trimester amount (DZD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(help_text='e.g. Frais de scolarité 2026-2027', max_length=200),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(help_text='Date the payment was physically received')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(help_text='Expiry date — status computed from this')),
                ('payment_method', models.CharField(choices=[('especes', 'Espèces'), ('baridimob', 'BaridiMob'), ('cib', 'CIB'), ('virement', 'Virement bancaire')], max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Auto-generated, e.g. PAY-2026-00001', max_length=30, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré')], default='actif', help_text='Auto-computed: actif if period_end >= today, else expire', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feestructure')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
