# Generated by Django 5.1.15 on 2026-03-05 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_redesign_fee_structure_and_student_payment'),
        ('schools', '0005_add_absence_alert_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(blank=True, help_text='Default due date. Overridden per student in StudentFeeEnrollment.', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='section',
            field=models.ForeignKey(blank=True, help_text='If set, this fee applies only to that section (Primary/Middle/High).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.section'),
        ),
        migrations.CreateModel(
            name='StudentFeeEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_due', models.DecimalField(decimal_places=2, help_text='Total amount owed for this fee (DZD).', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cached total paid — refreshed on each payment.', max_digits=10)),
                ('due_date', models.DateField(help_text='Deadline for full payment.')),
                ('status', models.CharField(choices=[('PAID', 'Payé'), ('PARTIAL', 'Partiel'), ('UNPAID', 'Impayé'), ('LATE', 'En Retard')], default='UNPAID', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='finance.feestructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='fee_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_fee_enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'fee_structure')},
            },
        ),
    ]
