# Generated by Django 5.1.15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0004_school_available_streams"),
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ─── MedicalRecord ──────────────────────────────────────
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("weight_height_history", models.JSONField(blank=True, default=list)),
                (
                    "current_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "current_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "treating_doctor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "treating_doctor_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mutuelle / Assurance",
                        max_length=255,
                    ),
                ),
                (
                    "cnas_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "casnos_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_medical_records",
                "ordering": ["-created_at"],
            },
        ),
        # ─── MedicalHistory ─────────────────────────────────────
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("CHRONIC", "Maladie chronique"),
                            ("CHILDHOOD", "Maladie infantile"),
                            ("SURGERY", "Intervention chirurgicale"),
                            ("HOSPITALISATION", "Hospitalisation"),
                            ("FAMILY", "Antécédent familial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_name", models.CharField(max_length=255)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True, default="")),
                (
                    "specialist_doctor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_ongoing", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="infirmerie.medicalrecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_medical_history",
                "ordering": ["-diagnosis_date", "-created_at"],
            },
        ),
        # ─── Allergy ────────────────────────────────────────────
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("MEDICATION", "Médicamenteuse"),
                            ("FOOD", "Alimentaire"),
                            ("ENVIRONMENTAL", "Environnementale"),
                            ("INSECT", "Piqûre d'insecte"),
                            ("CONTACT", "Contact"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allergen_name", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Légère"),
                            ("MODERATE", "Modérée"),
                            ("SEVERE", "Sévère"),
                            ("ANAPHYLACTIC", "Anaphylactique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("symptoms", models.TextField(blank=True, default="")),
                (
                    "emergency_protocol",
                    models.TextField(
                        blank=True, default="", help_text="Conduite à tenir"
                    ),
                ),
                ("has_epipen", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="infirmerie.medicalrecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_allergies",
                "ordering": ["-severity", "allergen_name"],
            },
        ),
        # ─── Medication ─────────────────────────────────────────
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dci_name",
                    models.CharField(
                        help_text="Dénomination Commune Internationale", max_length=255
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("dosage", models.CharField(max_length=100)),
                (
                    "administration_route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Voie orale"),
                            ("SUBLINGUAL", "Sublinguale"),
                            ("INJECTION", "Injectable"),
                            ("INHALATION", "Inhalation"),
                            ("TOPICAL", "Topique"),
                            ("RECTAL", "Rectale"),
                            ("EYE_DROP", "Collyre"),
                            ("OTHER", "Autre"),
                        ],
                        default="ORAL",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("1X_DAY", "1 fois/jour"),
                            ("2X_DAY", "2 fois/jour"),
                            ("3X_DAY", "3 fois/jour"),
                            ("AS_NEEDED", "Si besoin (SOS)"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("OTHER", "Autre"),
                        ],
                        default="1X_DAY",
                        max_length=20,
                    ),
                ),
                (
                    "schedule_times",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Horaires: ['08:00','12:00','18:00']",
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("stock_alert_threshold", models.PositiveIntegerField(default=5)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "prescribing_doctor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "prescription_file",
                    models.FileField(
                        blank=True, null=True, upload_to="infirmerie/prescriptions/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="infirmerie.medicalrecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_medications",
                "ordering": ["-is_active", "dci_name"],
            },
        ),
        # ─── Vaccination ────────────────────────────────────────
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("vaccine_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DONE", "Fait"),
                            ("NOT_DONE", "Non fait"),
                            ("OVERDUE", "En retard"),
                            ("SCHEDULED", "Planifié"),
                        ],
                        default="NOT_DONE",
                        max_length=20,
                    ),
                ),
                ("administration_date", models.DateField(blank=True, null=True)),
                (
                    "administered_at",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Lieu/établissement",
                        max_length=255,
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="infirmerie.medicalrecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_vaccinations",
                "ordering": ["vaccine_name", "-administration_date"],
            },
        ),
        # ─── Consultation ───────────────────────────────────────
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("HEADACHE", "Maux de tête"),
                            ("STOMACH", "Maux de ventre"),
                            ("FEVER", "Fièvre"),
                            ("INJURY", "Blessure / Traumatisme"),
                            ("ALLERGY_REACTION", "Réaction allergique"),
                            ("ASTHMA", "Crise d'asthme"),
                            ("DIABETES", "Malaise diabétique"),
                            ("EPILEPSY", "Crise d'épilepsie"),
                            ("NAUSEA", "Nausée / Vomissement"),
                            ("DIZZINESS", "Vertige / Malaise"),
                            ("EYE", "Problème oculaire"),
                            ("DENTAL", "Problème dentaire"),
                            ("SKIN", "Problème cutané"),
                            ("PSYCHOLOGICAL", "Motif psychologique"),
                            ("MEDICATION_ADMIN", "Administration de médicament"),
                            ("FOLLOW_UP", "Suivi / Contrôle"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(
                        blank=True, default="", help_text="Motif texte libre"
                    ),
                ),
                ("symptoms_description", models.TextField(blank=True, default="")),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°C",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "spo2",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="%", null=True
                    ),
                ),
                (
                    "pulse",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="bpm", null=True
                    ),
                ),
                (
                    "blood_sugar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="g/L",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "care_provided",
                    models.TextField(
                        blank=True, default="", help_text="Soins prodigués"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("RETURN_CLASS", "Retour en classe"),
                            ("REST_ROOM", "Repos à l'infirmerie"),
                            ("CONTACT_PARENT", "Contact parent"),
                            ("SENT_HOME", "Renvoi au domicile"),
                            ("EMERGENCY", "Urgences médicales"),
                            ("HOSPITAL_REFERRAL", "Orientation hôpital"),
                            ("OTHER", "Autre"),
                        ],
                        default="RETURN_CLASS",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=0)),
                ("observations", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="infirmerie/consultations/"
                    ),
                ),
                ("parent_contacted", models.BooleanField(default=False)),
                ("parent_contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nurse_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infirmerie_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_consultations",
                "ordering": ["-consultation_datetime"],
            },
        ),
        # ─── Disability ─────────────────────────────────────────
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disability_type",
                    models.CharField(
                        choices=[
                            ("MOTOR", "Moteur"),
                            ("VISUAL", "Visuel"),
                            ("HEARING", "Auditif"),
                            ("COGNITIVE", "Cognitif"),
                            ("LEARNING", "Trouble de l'apprentissage"),
                            ("SPEECH", "Trouble du langage"),
                            ("AUTISM", "TSA"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "autonomy_level",
                    models.CharField(
                        choices=[
                            ("FULL", "Autonomie complète"),
                            ("PARTIAL", "Autonomie partielle"),
                            ("ASSISTED", "Assistance requise"),
                            ("FULL_ASSISTANCE", "Assistance complète"),
                        ],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                (
                    "school_accommodations",
                    models.TextField(
                        blank=True, default="", help_text="Aménagements scolaires"
                    ),
                ),
                (
                    "pap_file",
                    models.FileField(
                        blank=True,
                        help_text="Plan d'Accompagnement Personnalisé",
                        null=True,
                        upload_to="infirmerie/pap/",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabilities",
                        to="infirmerie.medicalrecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_disabilities",
                "ordering": ["-created_at"],
            },
        ),
        # ─── PsychologicalRecord ─────────────────────────────────
        migrations.CreateModel(
            name="PsychologicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("vulnerability_report", models.TextField(blank=True, default="")),
                ("is_in_therapy", models.BooleanField(default=False)),
                (
                    "therapist_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "therapist_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("family_situation_notes", models.TextField(blank=True, default="")),
                ("follow_up_notes", models.TextField(blank=True, default="")),
                ("last_session_date", models.DateField(blank=True, null=True)),
                ("next_session_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychological_records",
                        to="infirmerie.medicalrecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_psychological_records",
                "ordering": ["-created_at"],
            },
        ),
        # ─── EmergencyProtocol ──────────────────────────────────
        migrations.CreateModel(
            name="EmergencyProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("ANAPHYLAXIS", "Choc anaphylactique"),
                            ("ASTHMA_ATTACK", "Crise d'asthme sévère"),
                            ("EPILEPTIC_SEIZURE", "Crise d'épilepsie"),
                            ("DIABETIC_EMERGENCY", "Urgence diabétique"),
                            ("CARDIAC", "Arrêt cardiaque"),
                            ("TRAUMA", "Traumatisme grave"),
                            ("HEMORRHAGE", "Hémorragie"),
                            ("FRACTURE", "Fracture"),
                            ("BURN", "Brûlure"),
                            ("POISONING", "Intoxication"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("protocol_steps", models.JSONField(default=list)),
                (
                    "triggers",
                    models.TextField(
                        blank=True, default="", help_text="Signes déclencheurs"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_emergency_protocols",
                "ordering": ["emergency_type"],
            },
        ),
        # ─── EmergencyEvent ─────────────────────────────────────
        migrations.CreateModel(
            name="EmergencyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("ANAPHYLAXIS", "Choc anaphylactique"),
                            ("ASTHMA_ATTACK", "Crise d'asthme sévère"),
                            ("EPILEPTIC_SEIZURE", "Crise d'épilepsie"),
                            ("DIABETIC_EMERGENCY", "Urgence diabétique"),
                            ("CARDIAC", "Arrêt cardiaque"),
                            ("TRAUMA", "Traumatisme grave"),
                            ("HEMORRHAGE", "Hémorragie"),
                            ("FRACTURE", "Fracture"),
                            ("BURN", "Brûlure"),
                            ("POISONING", "Intoxication"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "En cours"),
                            ("RESOLVED", "Résolu"),
                            ("TRANSFERRED", "Transféré"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actions_taken",
                    models.JSONField(
                        default=list, help_text="[{'time':'HH:MM','action':'...'}]"
                    ),
                ),
                (
                    "liaison_report_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Fiche de liaison médicale PDF",
                        null=True,
                        upload_to="infirmerie/emergencies/",
                    ),
                ),
                ("post_emergency_report", models.TextField(blank=True, default="")),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_notified_at", models.DateTimeField(blank=True, null=True)),
                ("emergency_services_called", models.BooleanField(default=False)),
                (
                    "consultation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_event",
                        to="infirmerie.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="infirmerie.emergencyprotocol",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_emergency_events",
                "ordering": ["-started_at"],
            },
        ),
        # ─── InfirmeryMessage ───────────────────────────────────
        migrations.CreateModel(
            name="InfirmeryMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("CONSULTATION_DONE", "Consultation effectuée"),
                            ("MEDICATION_REMINDER", "Rappel médicament"),
                            ("VACCINATION_REMINDER", "Rappel vaccination"),
                            ("REST_NOTIFICATION", "Notification de repos"),
                            ("SENT_HOME", "Renvoi au domicile"),
                            ("EMERGENCY_ALERT", "Alerte urgence"),
                            ("CUSTOM", "Message personnalisé"),
                        ],
                        default="CUSTOM",
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="infirmerie/messages/"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_infirmerie_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_infirmerie_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infirmerie_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_messages",
                "ordering": ["-created_at"],
            },
        ),
        # ─── AbsenceJustification ───────────────────────────────
        migrations.CreateModel(
            name="AbsenceJustification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("absence_date_start", models.DateField()),
                ("absence_date_end", models.DateField()),
                ("generic_reason", models.CharField(max_length=255)),
                (
                    "medical_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="infirmerie/certificates/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Soumise"),
                            ("VALIDATED", "Validée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="justifications",
                        to="infirmerie.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_absences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_justifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_justifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_absence_justifications",
                "ordering": ["-created_at"],
            },
        ),
        # ─── EpidemicAlert ──────────────────────────────────────
        migrations.CreateModel(
            name="EpidemicAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("disease_name", models.CharField(max_length=255)),
                ("case_count", models.PositiveIntegerField(default=1)),
                ("detection_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("WATCH", "Surveillance"),
                            ("WARNING", "Alerte"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="WATCH",
                        max_length=20,
                    ),
                ),
                ("is_contagious", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("actions_taken", models.TextField(blank=True, default="")),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epidemic_alerts",
                        to="academics.classroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_epidemic_alerts",
                "ordering": ["-detection_date"],
            },
        ),
        # ─── ContagiousDisease ──────────────────────────────────
        migrations.CreateModel(
            name="ContagiousDisease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("disease_name", models.CharField(max_length=255)),
                ("onset_date", models.DateField()),
                (
                    "recommended_eviction_days",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("authorized_return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "En cours"),
                            ("EVICTION", "En éviction"),
                            ("CLEARED", "Guéri / Autorisé"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epidemic_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_cases",
                        to="infirmerie.epidemicalert",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contagious_diseases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "infirmerie_contagious_diseases",
                "ordering": ["-onset_date"],
            },
        ),
    ]
