# Generated by Django 5.1.15 on 2026-03-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_algerian_school_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='e.g. 1AM-A', max_length=50),
        ),
        migrations.AlterField(
            model_name='stream',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abbreviated name for UI, e.g. Sciences', max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. MATH', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='e.g. Mathématiques', max_length=100),
        ),
    ]
