# Generated by Django 5.1.15 on 2026-03-04 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_class_name_alter_stream_short_name_and_more'),
        ('schools', '0004_school_available_streams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school'),
        ),
    ]
