# Generated by Django 5.1.15 on 2026-03-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_unique_subject_code_per_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='color',
            field=models.CharField(blank=True, default='#3b82f6', help_text='Hex color for UI display', max_length=7),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True for admin-created custom streams/groups'),
        ),
    ]
