# Generated by Django 5.1.15 on 2026-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_stream_custom_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True for admin-created subjects (not from MEN curriculum)'),
        ),
    ]
