# Generated by Django 5.1.15 on 2026-03-05 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_is_custom'),
        ('schools', '0004_school_available_streams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='schools.academicyear'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='room_name',
            field=models.CharField(blank=True, help_text='Physical room name (legacy — prefer room FK)', max_length=50),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. Salle 101, Labo Physique, etc.', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code, e.g. S101, LAB-P', max_length=20)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Salle de classe'), ('LAB', 'Laboratoire'), ('COMPUTER_LAB', 'Salle informatique'), ('LIBRARY', 'Bibliothèque'), ('GYM', 'Gymnase'), ('ART_ROOM', "Salle d'art"), ('MUSIC_ROOM', 'Salle de musique'), ('MEETING_ROOM', 'Salle de réunion'), ('AUDITORIUM', 'Amphithéâtre'), ('OTHER', 'Autre')], default='CLASSROOM', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=35, help_text='Maximum number of people')),
                ('floor', models.CharField(blank=True, help_text='e.g. RDC, 1er, 2e', max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True, help_text='False if room is under maintenance or unusable')),
                ('equipment', models.TextField(blank=True, help_text='Equipment list: projector, whiteboard, computers, etc.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Physical room — used for conflict detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='academics.room'),
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_availability',
                'ordering': ['teacher', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_room_name_per_school'),
        ),
    ]
