# Generated by Django 5.1.15 on 2026-03-05 20:09

import apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_room_teacher_availability'),
        ('chat', '0002_conversation_message_models'),
        ('schools', '0005_add_absence_alert_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='room_type',
            field=models.CharField(choices=[('DIRECT', 'Direct (legacy)'), ('TEACHER_PARENT', 'Teacher — Parent'), ('TEACHER_STUDENT', 'Teacher — Student'), ('ADMIN_PARENT', 'Admin — Parent')], default='DIRECT', help_text='Classification of this 1-to-1 conversation.', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('CLASS_BROADCAST', 'Class broadcast'), ('ADMIN_BROADCAST', 'Admin broadcast'), ('TEACHER_PARENT_GROUP', 'Teacher — Parents group'), ('TEACHER_STUDENT_GROUP', 'Teacher — Students group')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('related_class', models.ForeignKey(blank=True, help_text='Linked class for CLASS_BROADCAST / teacher-group rooms.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='schools.school')),
            ],
            options={
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.chat.models.room_attachment_path)),
                ('attachment_type', models.CharField(blank=True, choices=[('image', 'Image'), ('document', 'Document')], max_length=20, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_room_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('is_muted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_room_memberships',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
